-- Seed data generated from the frontend's src/data/services.js

INSERT INTO service_offerings (slug, icon, accent, title, tagline, description, highlights, tech_stack, ideal_for, display_order) VALUES
('web-development', 'Globe', 'sky', 'Web Development', 'Custom portals, React & full-stack apps',
 'We design and build fast, scalable web applications and business portals — from customer-facing products to internal enterprise dashboards — using modern, battle-tested technology.',
 '[{"title":"Responsive, accessible interfaces","description":"Interfaces built with React and Tailwind that work smoothly across every device and screen size."},{"title":"Scalable backend APIs","description":"Robust services in Node.js and Spring Boot designed to handle real production traffic."},{"title":"Performance-first delivery","description":"Server-side rendering, caching and code-splitting where it actually moves the needle."},{"title":"Secure by default","description":"Role-based access, encrypted data handling and audit-ready authentication flows."}]'::jsonb,
 '["React","Next.js","Node.js","Spring Boot","PostgreSQL","Tailwind CSS"]'::jsonb,
 '["SaaS products","Internal business portals","Customer-facing platforms","E-commerce storefronts"]'::jsonb,
 10),
('mobile-app-development', 'Smartphone', 'violet', 'Mobile App Development', 'Native & cross-platform iOS/Android',
 'We build high-performance mobile applications that feel native, ship faster with cross-platform frameworks, and scale comfortably with your user base.',
 '[{"title":"Near-native performance","description":"React Native and Flutter builds tuned to feel as smooth as fully native apps."},{"title":"Offline-first architecture","description":"Local data sync, background updates and push notifications that work in poor connectivity."},{"title":"Store-ready release management","description":"End-to-end App Store and Play Store submission, versioning and rollout support."},{"title":"Built-in observability","description":"Analytics and crash reporting wired in from day one, not bolted on later."}]'::jsonb,
 '["React Native","Flutter","Swift","Kotlin","Firebase"]'::jsonb,
 '["Consumer apps","Field-service tools","On-demand marketplaces","Internal ops apps"]'::jsonb,
 20),
('custom-software', 'Code2', 'indigo', 'Custom Software', 'Enterprise business logic & automations',
 'When off-the-shelf tools stop fitting how your business actually works, we build tailored software around your exact processes and rules.',
 '[{"title":"Deep process discovery","description":"We map how your teams really work before writing a single line of code."},{"title":"Workflow automation","description":"Approval routing, notifications and status tracking that replace manual spreadsheets."},{"title":"Custom reporting","description":"Live dashboards built around the metrics that matter to your operations."},{"title":"Seamless integrations","description":"Clean connections into the internal tools and data sources you already rely on."}]'::jsonb,
 '["Java","Spring Boot","Python","REST APIs","PostgreSQL","Redis"]'::jsonb,
 '["Operations automation","Internal tooling","Legacy system replacement","Workflow platforms"]'::jsonb,
 30),
('enterprise-solutions', 'Building2', 'emerald', 'Enterprise Solutions', 'ERP, CRM, and cloud integrations',
 'We help larger organizations modernize core systems, connect fragmented tools, and build enterprise-grade platforms that scale safely across teams and regions.',
 '[{"title":"ERP & CRM implementation","description":"Configuration and customization of enterprise systems around your real processes."},{"title":"Legacy modernization","description":"Phased migration from monoliths to maintainable, independently deployable services."},{"title":"Enterprise-grade security","description":"Access controls, audit trails and compliance safeguards built in from the start."},{"title":"Multi-team rollout support","description":"Deployment and change-management support across departments and regions."}]'::jsonb,
 '["Java","Kubernetes","Kafka","AWS","Azure","PostgreSQL"]'::jsonb,
 '["Large enterprises","Regulated industries","Multi-department platforms","Public sector systems"]'::jsonb,
 40),
('ui-ux-design', 'Palette', 'rose', 'UI/UX Design', 'Modern interfaces and product prototyping',
 'We design interfaces people actually enjoy using — grounded in research, validated with real prototypes, and built to convert.',
 '[{"title":"User research & journey mapping","description":"Understanding real user behavior before committing to a design direction."},{"title":"Interactive prototypes","description":"Clickable Figma prototypes you can test with real users before development starts."},{"title":"Reusable design systems","description":"Component libraries that keep your product consistent as it grows."},{"title":"Conversion-focused UX","description":"Interfaces designed around clear user goals and measurable outcomes."}]'::jsonb,
 '["Figma","Prototyping","Design Systems","User Testing"]'::jsonb,
 '["New product design","Product redesigns","Design system creation","UX audits"]'::jsonb,
 50),
('cloud-devops', 'Cloud', 'amber', 'Cloud & DevOps', 'CI/CD pipelines, Docker & AWS hosting',
 'We build the infrastructure and delivery pipelines that let your team ship confidently, scale predictably, and stay in control of cost and uptime.',
 '[{"title":"Automated CI/CD","description":"Pipelines that test, build and deploy on every change, with rollback built in."},{"title":"Containerized deployments","description":"Docker and Kubernetes setups that make scaling services a configuration change, not a project."},{"title":"Infrastructure as code","description":"Reproducible environments defined in Terraform, not manual console clicks."},{"title":"Monitoring & cost control","description":"Alerting, dashboards and regular cost audits so surprises stay rare."}]'::jsonb,
 '["AWS","Docker","Kubernetes","Terraform","GitHub Actions"]'::jsonb,
 '["Scaling startups","Deployment modernization","Reliability audits","Cost optimization"]'::jsonb,
 60);
